# Generated by Django 5.2.15 on 2026-07-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_category_listing_image_listing_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
